// Resource aliases from WPF UI 4.3.0 Light/Dark theme dictionaries (MIT).
// https://github.com/lepoco/wpfui/blob/4.3.0/src/Wpf.Ui/Resources/Theme/Light.xaml
// Copyright (c) Leszek Pomianowski and WPF UI Contributors. See docs/licenses/WPF-UI.txt.
namespace ToDoList.App.Services;

internal static class ThemeBrushAliases
{
    // Explicit aliases avoid reading already-overridden resources on the next switch.
    internal static readonly IReadOnlyDictionary<string, string[]> ByColor = new Dictionary<string, string[]>
    {
        ["ApplicationBackgroundColor"] = ["ApplicationBackgroundBrush", "WindowBackground", "LoadingScreenBackground"],
        ["KeyboardFocusBorderColor"] = ["KeyboardFocusBorderColorBrush"],
        ["TextFillColorPrimary"] = ["TextFillColorPrimaryBrush", "BreadcrumbBarNormalForegroundBrush", "BreadcrumbBarCurrentNormalForegroundBrush", "ButtonForeground", "ButtonForegroundPointerOver", "CalendarViewForeground", "CalendarViewNavigationButtonForeground", "CardForeground", "CardForegroundPointerOver", "CheckBoxForeground", "ComboBoxForeground", "ComboBoxItemForeground", "ComboBoxItemForegroundSelected", "ContentDialogForeground", "ContextMenuForeground", "ExpanderHeaderForeground", "WindowForeground", "InfoBarTitleForeground", "ListBoxItemForeground", "ListViewItemForeground", "LoadingScreenForeground", "MessageBoxForeground", "NavigationViewItemForeground", "NavigationViewItemForegroundPointerOver", "NavigationViewItemForegroundLeftFluent", "NavigationViewItemForegroundPointerOverLeftFluent", "RadioButtonForeground", "SnackBarForeground", "TabViewForeground", "TabViewItemForegroundSelected", "TextControlForeground", "TimePickerButtonForegroundPointerOver", "ToggleButtonForeground", "ToggleSwitchContentForeground", "ToolTipForeground", "TreeViewItemForeground"],
        ["TextFillColorSecondary"] = ["TextFillColorSecondaryBrush", "BreadcrumbBarHoverForegroundBrush", "ButtonForegroundPressed", "CardForegroundPressed", "ComboBoxDropDownGlyphForeground", "LabelForeground", "MenuBarItemTextForegroundPressed", "NavigationViewItemForegroundPressed", "TextControlButtonForeground", "TimePickerButtonForegroundDefault", "TimePickerButtonForegroundPressed", "ToggleButtonForegroundPressed", "ToggleSwitchKnobFillOff", "ToggleSwitchKnobFillOffPointerOver", "ToggleSwitchKnobFillOffPressed"],
        ["TextFillColorTertiary"] = ["TextFillColorTertiaryBrush"],
        ["TextFillColorDisabled"] = ["TextFillColorDisabledBrush", "ButtonForegroundDisabled", "CardForegroundDisabled", "CheckBoxForegroundUncheckedDisabled", "ComboBoxForegroundDisabled", "ExpanderHeaderDisabledForeground", "RadioButtonForegroundDisabled", "TextControlForegroundDisabled", "TimePickerButtonForegroundDisabled", "ToggleButtonForegroundDisabled", "ToggleSwitchContentForegroundDisabled", "ToggleSwitchKnobFillOffDisabled"],
        ["TextPlaceholderColor"] = ["TextPlaceholderColorBrush", "TextControlPlaceholderForeground"],
        ["TextFillColorInverse"] = ["TextFillColorInverseBrush", "InfoBadgeValueForeground"],
        ["AccentTextFillColorDisabled"] = ["AccentTextFillColorDisabledBrush", "HyperlinkButtonForegroundDisabled"],
        ["TextOnAccentFillColorSelectedText"] = ["TextOnAccentFillColorSelectedTextBrush"],
        ["TextOnAccentFillColorPrimary"] = ["TextOnAccentFillColorPrimaryBrush", "BadgeForeground", "AccentButtonForeground", "AccentButtonForegroundPointerOver", "CalendarViewTodayForeground", "CheckBoxCheckGlyphForeground", "ListBoxItemSelectedForegroundThemeBrush", "RadioButtonCheckGlyphFill", "ToggleButtonForegroundChecked", "ToggleSwitchKnobFillOn", "ToggleSwitchKnobFillOnPointerOver", "ToggleSwitchKnobFillOnPressed"],
        ["TextOnAccentFillColorSecondary"] = ["TextOnAccentFillColorSecondaryBrush", "AccentButtonForegroundPressed", "ToggleButtonForegroundCheckedPressed"],
        ["TextOnAccentFillColorDisabled"] = ["TextOnAccentFillColorDisabledBrush", "ToggleButtonForegroundCheckedDisabled", "ToggleSwitchKnobFillOnDisabled"],
        ["ControlFillColorDefault"] = ["ControlFillColorDefaultBrush", "ButtonBackground", "ComboBoxBackground", "ComboBoxBackgroundFocused", "NavigationViewItemBackgroundSelectedLeftFluent", "TextControlBackground", "ToggleButtonBackground"],
        ["ControlFillColorSecondary"] = ["ControlFillColorSecondaryBrush", "ButtonBackgroundPointerOver", "CardBackgroundPointerOver", "ComboBoxBackgroundPointerOver", "TextControlBackgroundPointerOver", "TimePickerButtonBackgroundPointerOver", "ToggleButtonBackgroundPointerOver"],
        ["ControlFillColorTertiary"] = ["ControlFillColorTertiaryBrush", "ButtonBackgroundPressed", "CardBackgroundPressed", "TimePickerButtonBackground", "TimePickerButtonBackgroundPressed", "ToggleButtonBackgroundPressed"],
        ["ControlFillColorDisabled"] = ["ControlFillColorDisabledBrush", "ButtonBackgroundDisabled", "CardBackgroundDisabled", "ComboBoxBackgroundDisabled", "TextControlBackgroundDisabled", "TimePickerButtonBackgroundDisabled", "ToggleButtonBackgroundDisabled"],
        ["ControlFillColorTransparent"] = ["ControlFillColorTransparentBrush", "AccentButtonBorderBrushPressed", "ProgressBarIndeterminateBackground", "ProgressRingBackgroundThemeBrush", "ToggleButtonBorderBrushCheckedPressed", "ToggleButtonBorderBrushCheckedDisabled"],
        ["ControlFillColorInputActive"] = ["ControlFillColorInputActiveBrush", "CalendarViewBackground", "TextControlBackgroundFocused"],
        ["ControlStrongFillColorDefault"] = ["ControlStrongFillColorDefaultBrush", "ScrollBarButtonArrowForeground", "ScrollBarThumbFill", "SliderTrackFill", "SliderTrackFillPointerOver", "SliderTickBarFill"],
        ["ControlStrongFillColorDisabled"] = ["ControlStrongFillColorDisabledBrush"],
        ["ControlSolidFillColorDefault"] = ["ControlSolidFillColorDefaultBrush", "SliderOuterThumbBackground"],
        ["SubtleFillColorTransparent"] = ["SubtleFillColorTransparentBrush", "CheckBoxCheckBorderBrush", "ScrollBarButtonBackground", "HyperlinkButtonBackground", "MenuBarBackground", "NavigationViewItemBackground", "NavigationViewItemBorderBrush", "TabViewBackground", "TreeViewItemBackground"],
        ["SubtleFillColorSecondary"] = ["SubtleFillColorSecondaryBrush", "CalendarViewItemBackgroundPointerOver", "ComboBoxItemBackgroundSelected", "HyperlinkButtonBackgroundPointerOver", "ListViewItemBackgroundPointerOver", "MenuBarItemBackgroundSelected", "NavigationViewItemBackgroundPointerOver", "NavigationViewItemBackgroundSelected", "TreeViewItemBackgroundPointerOver", "TreeViewItemBackgroundSelected"],
        ["SubtleFillColorTertiary"] = ["SubtleFillColorTertiaryBrush", "CalendarViewItemBackgroundPressed", "HyperlinkButtonBackgroundPressed", "MenuBarItemBackgroundPressed", "NavigationViewItemBackgroundPressed"],
        ["SubtleFillColorDisabled"] = ["SubtleFillColorDisabledBrush", "HyperlinkButtonBackgroundDisabled"],
        ["ControlAltFillColorTransparent"] = ["ControlAltFillColorTransparentBrush"],
        ["ControlAltFillColorSecondary"] = ["ControlAltFillColorSecondaryBrush", "CheckBoxBackground", "RadioButtonOuterEllipseFill", "ToggleSwitchFillOff"],
        ["ControlAltFillColorTertiary"] = ["ControlAltFillColorTertiaryBrush", "CheckBoxCheckBackgroundFillUncheckedPointerOver", "MenuBarItemBorderBrush", "RadioButtonOuterEllipseFillPointerOver", "ToggleSwitchFillOffPointerOver"],
        ["ControlAltFillColorQuarternary"] = ["ControlAltFillColorQuarternaryBrush", "CheckBoxCheckBackgroundFillUncheckedPressed", "RadioButtonOuterEllipseFillPressed", "ToggleSwitchFillOffPressed"],
        ["ControlAltFillColorDisabled"] = ["ControlAltFillColorDisabledBrush", "CheckBoxCheckBackgroundFillUncheckedDisabled", "RadioButtonOuterEllipseFillDisabled", "ToggleSwitchFillOffDisabled"],
        ["ControlOnImageFillColorDefault"] = ["ControlOnImageFillColorDefaultBrush"],
        ["ControlOnImageFillColorSecondary"] = ["ControlOnImageFillColorSecondaryBrush"],
        ["ControlOnImageFillColorTertiary"] = ["ControlOnImageFillColorTertiaryBrush"],
        ["ControlOnImageFillColorDisabled"] = ["ControlOnImageFillColorDisabledBrush"],
        ["AccentFillColorDisabled"] = ["AccentFillColorDisabledBrush", "ToggleButtonBackgroundCheckedDisabled", "ToggleSwitchStrokeOnDisabled", "ToggleSwitchFillOnDisabled"],
        ["ControlStrokeColorDefault"] = ["ControlStrokeColorDefaultBrush", "ButtonBorderBrushPressed", "ButtonBorderBrushDisabled", "CalendarViewBorderBrush", "CardBorderBrushPressed", "CardBorderBrushDisabled", "ComboBoxBorderBrushDisabled", "ProgressBarBorderBrush", "TextControlBorderBrushDisabled", "TimePickerButtonBorderBrushPressed", "TimePickerButtonBorderBrushDisabled", "ToggleButtonBorderBrushDisabled", "ToggleButtonBorderBrushPressed"],
        ["ControlStrokeColorSecondary"] = ["ControlStrokeColorSecondaryBrush"],
        ["ControlStrokeColorTertiary"] = ["ControlStrokeColorTertiaryBrush"],
        ["ControlStrokeColorOnAccentDefault"] = ["ControlStrokeColorOnAccentDefaultBrush"],
        ["ControlStrokeColorOnAccentSecondary"] = ["ControlStrokeColorOnAccentSecondaryBrush"],
        ["ControlStrokeColorOnAccentTertiary"] = ["ControlStrokeColorOnAccentTertiaryBrush"],
        ["ControlStrokeColorOnAccentDisabled"] = ["ControlStrokeColorOnAccentDisabledBrush"],
        ["ControlStrokeColorForStrongFillWhenOnImage"] = ["ControlStrokeColorForStrongFillWhenOnImageBrush"],
        ["CardStrokeColorDefault"] = ["CardStrokeColorDefaultBrush", "CardBorderBrush", "ContentDialogSeparatorBorderBrush", "ExpanderHeaderBorderBrush", "ExpanderHeaderBorderPointerOverBrush", "ExpanderHeaderDisabledBorderBrush", "InfoBarBorderBrush", "InfoBarErrorSeverityBorderBrush", "InfoBarWarningSeverityBorderBrush", "InfoBarSuccessSeverityBorderBrush", "InfoBarInformationalSeverityBorderBrush", "MessageBoxSeparatorBorderBrush", "NavigationViewContentGridBorderBrush", "TabViewBorderBrush", "TabViewSelectedItemBorderBrush"],
        ["CardStrokeColorDefaultSolid"] = ["CardStrokeColorDefaultSolidBrush"],
        ["ControlStrongStrokeColorDefault"] = ["ControlStrongStrokeColorDefaultBrush", "CheckBoxBorderBrush", "ProgressBarBackground", "RadioButtonOuterEllipseStroke", "ToggleSwitchStrokeOff", "ToggleSwitchStrokeOffPointerOver", "ToggleSwitchStrokeOffPressed"],
        ["ControlStrongStrokeColorDisabled"] = ["ControlStrongStrokeColorDisabledBrush", "CheckBoxCheckBackgroundStrokeUncheckedDisabled", "RadioButtonOuterEllipseStrokePressed", "RadioButtonOuterEllipseStrokeDisabled", "ToggleSwitchStrokeOffDisabled"],
        ["SurfaceStrokeColorDefault"] = ["SurfaceStrokeColorDefaultBrush", "ComboBoxDropDownBorderBrush", "ContentDialogBorderBrush"],
        ["SurfaceStrokeColorFlyout"] = ["SurfaceStrokeColorFlyoutBrush", "ContextMenuBorderBrush", "FlyoutBorderBrush", "SnackBarBorderBrush", "ToolTipBorderBrush"],
        ["SurfaceStrokeColorInverse"] = ["SurfaceStrokeColorInverseBrush"],
        ["DividerStrokeColorDefault"] = ["DividerStrokeColorDefaultBrush", "NavigationViewItemSeparatorForeground", "SeparatorBorderBrush"],
        ["FocusStrokeColorOuter"] = ["FocusStrokeColorOuterBrush"],
        ["FocusStrokeColorInner"] = ["FocusStrokeColorInnerBrush"],
        ["CardBackgroundFillColorDefault"] = ["CardBackgroundFillColorDefaultBrush", "CardBackground", "ExpanderHeaderBackground"],
        ["CardBackgroundFillColorSecondary"] = ["CardBackgroundFillColorSecondaryBrush", "CardFooterBackground", "ExpanderContentBackground"],
        ["SmokeFillColorDefault"] = ["SmokeFillColorDefaultBrush", "ContentDialogSmokeFill"],
        ["LayerFillColorDefault"] = ["LayerFillColorDefaultBrush", "NavigationViewContentBackground"],
        ["LayerFillColorAlt"] = ["LayerFillColorAltBrush", "ContentDialogTopOverlay", "MessageBoxTopOverlay"],
        ["LayerOnAcrylicFillColorDefault"] = ["LayerOnAcrylicFillColorDefaultBrush"],
        ["LayerOnAccentAcrylicFillColorDefault"] = ["LayerOnAccentAcrylicFillColorDefaultBrush"],
        ["LayerOnMicaBaseAltFillColorDefault"] = ["LayerOnMicaBaseAltFillColorDefaultBrush"],
        ["LayerOnMicaBaseAltFillColorSecondary"] = ["LayerOnMicaBaseAltFillColorSecondaryBrush"],
        ["LayerOnMicaBaseAltFillColorTertiary"] = ["LayerOnMicaBaseAltFillColorTertiaryBrush"],
        ["LayerOnMicaBaseAltFillColorTransparent"] = ["LayerOnMicaBaseAltFillColorTransparentBrush", "TabViewItemHeaderBackground"],
        ["SolidBackgroundFillColorBase"] = ["SolidBackgroundFillColorBaseBrush", "ContentDialogBackground", "MessageBoxBackground"],
        ["SolidBackgroundFillColorSecondary"] = ["SolidBackgroundFillColorSecondaryBrush"],
        ["SolidBackgroundFillColorTertiary"] = ["SolidBackgroundFillColorTertiaryBrush", "TabViewItemHeaderBackgroundSelected"],
        ["SolidBackgroundFillColorQuarternary"] = ["SolidBackgroundFillColorQuarternaryBrush"],
        ["SolidBackgroundFillColorBaseAlt"] = ["SolidBackgroundFillColorBaseAltBrush"],
        ["SystemFillColorSuccess"] = ["SystemFillColorSuccessBrush", "InfoBadgeSuccessSeverityBackgroundBrush", "InfoBarSuccessSeverityIconBackground"],
        ["SystemFillColorCaution"] = ["SystemFillColorCautionBrush", "InfoBadgeCautionSeverityBackgroundBrush", "InfoBarWarningSeverityIconBackground"],
        ["SystemFillColorCritical"] = ["SystemFillColorCriticalBrush", "InfoBadgeCriticalSeverityBackgroundBrush", "InfoBarErrorSeverityIconBackground"],
        ["SystemFillColorNeutral"] = ["SystemFillColorNeutralBrush"],
        ["SystemFillColorSolidNeutral"] = ["SystemFillColorSolidNeutralBrush"],
        ["SystemFillColorAttentionBackground"] = ["SystemFillColorAttentionBackgroundBrush", "InfoBarInformationalSeverityBackgroundBrush"],
        ["SystemFillColorSuccessBackground"] = ["SystemFillColorSuccessBackgroundBrush", "InfoBarSuccessSeverityBackgroundBrush"],
        ["SystemFillColorCautionBackground"] = ["SystemFillColorCautionBackgroundBrush", "InfoBarWarningSeverityBackgroundBrush"],
        ["SystemFillColorCriticalBackground"] = ["SystemFillColorCriticalBackgroundBrush", "InfoBarErrorSeverityBackgroundBrush"],
        ["SystemFillColorNeutralBackground"] = ["SystemFillColorNeutralBackgroundBrush"],
        ["SystemFillColorSolidAttentionBackground"] = ["SystemFillColorSolidAttentionBackgroundBrush"],
        ["SystemFillColorSolidNeutralBackground"] = ["SystemFillColorSolidNeutralBackgroundBrush"],
        ["SystemAccentColorPrimary"] = ["BadgeBackground", "CalendarViewSelectedBackground", "CalendarViewSelectedBorderBrush", "CalendarViewTodayBackground", "CheckBoxCheckBackgroundFillChecked", "ComboBoxItemPillFillBrush", "HyperlinkButtonForegroundPressed", "InfoBarInformationalSeverityIconBackground", "ListBoxItemSelectedBackgroundThemeBrush", "ListViewItemPillFillBrush", "NavigationViewSelectionIndicatorForeground", "ProgressBarForeground", "ProgressRingForegroundThemeBrush", "RadioButtonOuterEllipseCheckedStroke", "RatingControlSelectedForeground", "SliderThumbBackground", "TextControlFocusedBorderBrush", "ThumbRateForeground", "ToggleButtonBackgroundChecked", "ToggleSwitchStrokeOn", "ToggleSwitchFillOn", "TreeViewItemSelectionIndicatorForeground"],
        ["AccentFillColorDefault"] = ["AccentButtonBackground"],
        ["AccentFillColorSecondary"] = ["AccentButtonBackgroundPointerOver", "CalendarViewSelectedBackgroundPointerOver", "CheckBoxCheckBackgroundFillCheckedPointerOver", "SliderThumbBackgroundPointerOver", "ToggleSwitchStrokeOnPointerOver", "ToggleSwitchFillOnPointerOver"],
        ["AccentFillColorTertiary"] = ["AccentButtonBackgroundPressed", "CheckBoxCheckBackgroundFillCheckedPressed", "RadioButtonOuterEllipseCheckedStrokePointerOver", "ToggleSwitchStrokeOnPressed", "ToggleSwitchFillOnPressed"],
        ["SystemAccentColorSecondary"] = ["ComboBoxBorderBrushFocused", "HyperlinkButtonForeground", "ToggleButtonForegroundCheckedPointerOver"],
        ["AcrylicBackgroundFillColorDefault"] = ["ComboBoxDropDownBackground", "ContextMenuBackground", "ScrollBarTrackFillPointerOver", "FlyoutBackground", "SnackBarBackground", "ToolTipBackground"],
        ["SystemAccentColorTertiary"] = ["HyperlinkButtonForegroundPointerOver", "ToggleButtonBackgroundCheckedPressed"],
        ["SystemFillColorAttention"] = ["InfoBadgeAttentionSeverityBackgroundBrush"],
        ["SystemFillColorInformational"] = ["InfoBadgeInformationalSeverityBackgroundBrush"],
    };
}
